spring:
  application:
    name: board
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dong
    password: ehdghks2602
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Zipkin 트레이싱 설정
  tracing:
    sampling:
      probability: 1.0   # 100% 샘플링 (운영 시 0.1 권장)

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

jwt:
  secret: "board-jwt-secret-key-must-be-32-chars-minimum!!"
  expiration-ms: 86400000

admin:
  default-id: "admin"
  default-password: "Admin1234!"
